local math = math or {}
return {
	["abs"] =        { tag = "var", contents = "math.abs",        value = math.abs,        },
	["acos"] =       { tag = "var", contents = "math.acos",       value = math.acos,       },
	["asin"] =       { tag = "var", contents = "math.asin",       value = math.asin,       },
	["atan"] =       { tag = "var", contents = "math.atan",       value = math.atan,       },
	["atan2"] =      { tag = "var", contents = "math.atan2",      value = math.atan2,      },
	["ceil"] =       { tag = "var", contents = "math.ceil",       value = math.ceil,       },
	["cos"] =        { tag = "var", contents = "math.cos",        value = math.cos,        },
	["cosh"] =       { tag = "var", contents = "math.cosh",       value = math.cosh,       },
	["deg"] =        { tag = "var", contents = "math.deg",        value = math.deg,        },
	["exp"] =        { tag = "var", contents = "math.exp",        value = math.exp,        },
	["floor"] =      { tag = "var", contents = "math.floor",      value = math.floor,      },
	["fmod"] =       { tag = "var", contents = "math.fmod",       value = math.fmod,       },
	["frexp"] =      { tag = "var", contents = "math.frexp",      value = math.frexp,      },
	["huge"] =       { tag = "var", contents = "math.huge",       value = math.huge,       },
	["ldexp"] =      { tag = "var", contents = "math.ldexp",      value = math.ldexp,      },
	["log"] =        { tag = "var", contents = "math.log",        value = math.log,        },
	["log10"] =      { tag = "var", contents = "math.log10",      value = math.log10,      },
	["max"] =        { tag = "var", contents = "math.max",        value = math.max,        },
	["min"] =        { tag = "var", contents = "math.min",        value = math.min,        },
	["modf"] =       { tag = "var", contents = "math.modf",       value = math.modf,       },
	["pi"] =         { tag = "var", contents = "math.pi",         value = math.pi,         },
	["pow"] =        { tag = "var", contents = "math.pow",        value = math.pow,        },
	["rad"] =        { tag = "var", contents = "math.rad",        value = math.rad,        },
	["random"] =     { tag = "var", contents = "math.random",     value = math.random,     },
	["randomseed"] = { tag = "var", contents = "math.randomseed", value = math.randomseed, },
	["sin"] =        { tag = "var", contents = "math.sin",        value = math.sin,        },
	["sinh"] =       { tag = "var", contents = "math.sinh",       value = math.sinh,       },
	["sqrt"] =       { tag = "var", contents = "math.sqrt",       value = math.sqrt,       },
	["tan"] =        { tag = "var", contents = "math.tan",        value = math.tan,        },
	["tanh"] =       { tag = "var", contents = "math.tanh",       value = math.tanh,       },
}
