local os = os or {}
return {
	["cancelAlarm"] =      { tag = "var", contents = "os.cancelAlarm",      value = os.cancelAlarm,      },
	["cancelTimer"] =      { tag = "var", contents = "os.cancelTimer",      value = os.cancelTimer,      },
	["clock"] =            { tag = "var", contents = "os.clock",            value = os.clock,            },
	["computerID"] =       { tag = "var", contents = "os.computerID",       value = os.computerID,       },
	["computerLabel"] =    { tag = "var", contents = "os.computerLabel",    value = os.computerLabel,    },
	["day"] =              { tag = "var", contents = "os.day",              value = os.day,              },
	["getComputerID"] =    { tag = "var", contents = "os.getComputerID",    value = os.getComputerID,    },
	["getComputerLabel"] = { tag = "var", contents = "os.getComputerLabel", value = os.getComputerLabel, },
	["loadAPI"] =          { tag = "var", contents = "os.loadAPI",          value = os.loadAPI,          },
	["pullEvent"] =        { tag = "var", contents = "os.pullEvent",        value = os.pullEvent,        },
	["pullEventRaw"] =     { tag = "var", contents = "os.pullEventRaw",     value = os.pullEventRaw,     },
	["queueEvent"] =       { tag = "var", contents = "os.queueEvent",       value = os.queueEvent,       },
	["reboot"] =           { tag = "var", contents = "os.reboot",           value = os.reboot,           },
	["run"] =              { tag = "var", contents = "os.run",              value = os.run,              },
	["setAlarm"] =         { tag = "var", contents = "os.setAlarm",         value = os.setAlarm,         },
	["setComputerLabel"] = { tag = "var", contents = "os.setComputerLabel", value = os.setComputerLabel, },
	["shutdown"] =         { tag = "var", contents = "os.shutdown",         value = os.shutdown,         },
	["sleep"] =            { tag = "var", contents = "os.sleep",            value = os.sleep,            },
	["startTimer"] =       { tag = "var", contents = "os.startTimer",       value = os.startTimer,       },
	["time"] =             { tag = "var", contents = "os.time",             value = os.time,             },
	["unloadAPI"] =        { tag = "var", contents = "os.unloadAPI",        value = os.unloadAPI,        },
	["version"] =          { tag = "var", contents = "os.version",          value = os.version,          },
}
