local term = term or {}
return {
	["blit"] =                { tag = "var", contents = "term.blit",                value = term.blit,                },
	["clear"] =               { tag = "var", contents = "term.clear",               value = term.clear,               },
	["clearLine"] =           { tag = "var", contents = "term.clearLine",           value = term.clearLine,           },
	["current"] =             { tag = "var", contents = "term.current",             value = term.current,             },
	["getBackgroundColor"] =  { tag = "var", contents = "term.getBackgroundColor",  value = term.getBackgroundColor,  },
	["getBackgroundColour"] = { tag = "var", contents = "term.getBackgroundColour", value = term.getBackgroundColour, },
	["getCursorPos"] =        { tag = "var", contents = "term.getCursorPos",        value = term.getCursorPos,        },
	["getSize"] =             { tag = "var", contents = "term.getSize",             value = term.getSize,             },
	["getTextColor"] =        { tag = "var", contents = "term.getTextColor",        value = term.getTextColor,        },
	["getTextColour"] =       { tag = "var", contents = "term.getTextColour",       value = term.getTextColour,       },
	["isColor"] =             { tag = "var", contents = "term.isColor",             value = term.isColor,             },
	["isColour"] =            { tag = "var", contents = "term.isColour",            value = term.isColour,            },
	["native"] =              { tag = "var", contents = "term.native",              value = term.native,              },
	["redirect"] =            { tag = "var", contents = "term.redirect",            value = term.redirect,            },
	["scroll"] =              { tag = "var", contents = "term.scroll",              value = term.scroll,              },
	["setBackgroundColor"] =  { tag = "var", contents = "term.setBackgroundColor",  value = term.setBackgroundColor,  },
	["setBackgroundColour"] = { tag = "var", contents = "term.setBackgroundColour", value = term.setBackgroundColour, },
	["setCursorBlink"] =      { tag = "var", contents = "term.setCursorBlink",      value = term.setCursorBlink,      },
	["setCursorPos"] =        { tag = "var", contents = "term.setCursorPos",        value = term.setCursorPos,        },
	["setTextColor"] =        { tag = "var", contents = "term.setTextColor",        value = term.setTextColor,        },
	["setTextColour"] =       { tag = "var", contents = "term.setTextColour",       value = term.setTextColour,       },
	["write"] =               { tag = "var", contents = "term.write",               value = term.write,               },
}
